name: Publish Site Changes

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102

    - name: Install dependencies
      run: dotnet restore /nologo
      working-directory: src
    - name: Build
      run: dotnet build --configuration Release --no-restore /nologo
      working-directory: src
    - name: Test
      run: dotnet test --no-restore --no-build --verbosity normal /nologo
      working-directory: src
    - name: Publish
      run: dotnet publish --no-restore --output "../package" --verbosity normal /nologo
      working-directory: src
            
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: CoronaVirusApi-RSA
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: package
